server:
    port: 9080

spring:
    datasource:
        url:
            jdbc:h2:tcp://localhost/~/jpashop
        username: sa
        password:
        driver-class-name: org.h2.Driver
    
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                default_batch_fetch_size: 1000
                show_sql: true
                format_sql: true
        open-in-view: true
    devtools:
        livereload:
            enabled: true
            port: 35730

logging:
    level:
        org.hibernate.sql: debug